name: CI/CD Pipeline for Imagify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend setup
      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm install

      - name: Run Backend Tests
        working-directory: ./server
        run: npm test

      # Frontend setup
      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./client
        run: npm run test -- --passWithNoTests

      - name: Build Frontend
        working-directory: ./client
        run: npm run build
