name: CI/CD Pipeline for Imagify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Setup server
      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm install

      - name: Run Backend Tests (optional)
        working-directory: ./server
        run: |
          echo "No tests yet" # Replace with: npm test

      # Setup client
      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install

      - name: Build Frontend
        working-directory: ./client
        run: npm run build
